fix No interface method startReplaceableGroup !! 1. ues com.google.accompanist:accompanist-coil replace dev.chrisbanes.accompanist:accompanist-coil
2. navigation-compose upgrade to 2.4.0-alpha02 !! (still error need fix)

requestBuilder can ref : https://github.com/google/accompanist/blob/350f4b99fe9c04a074c9e39e25cf0eb7786ef2d7/sample/src/main/java/com/google/accompanist/sample/coil/CoilBasicSample.kt#L87

Ref :  https://developer.android.com/jetpack/androidx/releases/compose-runtime#1.0.0-beta07

      Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
      java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. (Ia34e6)